#!/bin/bash

case $1 in
    on)
        xrandr --output DP-3 --auto --above eDP-1
        ;;
    off)
        xrandr --output DP-3 --off
        ;;
    *)
        echo "Argument must be one of 'on' or 'off'"
        ;;
esac
