#!/bin/bash

case $1 in
    on)
        xrandr --output eDP-1 --auto --output DP-3 --primary --auto --above eDP-1
        ;;
    only)
        xrandr --output eDP-1 --off --output DP-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal
        ;;
    uw)
        xrandr --output eDP-1 --primary --mode 1920x1080 --pos 760x1440 --rotate normal --output DP-3 --mode 3440x1440 --pos 0x0 --rotate normal
        ;;
    uwonly)
        xrandr --output eDP-1 --off --output DP-3 --primary --mode 3440x1440 --pos 0x0 --rotate normal
        ;;
    off)
        xrandr --output DP-3 --off
        ;;
    *)
        echo "Argument must be one of 'on', 'uw' or 'off'"
        ;;
esac
