#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

sudo apt-get update
sudo apt-get upgrade

# Install zsh
echo 'Install zsh'
echo '-----------'
sudo apt install zsh

# Install oh-my-zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

# Install Python
echo 'Install python'
echo '--------------'
sudo apt-get install -y python3

# Install pip
echo 'Install pip'
echo '-----------'
sudo apt-get install -y python3-pip

# Install nvm
echo 'Install nvm'
echo '-----------'
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Install node
echo 'Install node'
echo '------------'
nvm install node

# Install PHP
echo 'Install PHP'
echo '-----------'
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php8.1 php8.1-dev php8.1-xml -y --allow-unauthenticated

# Install composer
echo 'Install Composer'
echo '----------------'
curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
HASH=`curl -sS https://composer.github.io/installer.sig`
php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
composer --version

# Install ripgrep
echo 'Install ripgrep'
echo '---------------'
sudo apt-get install -y ripgrep

# Install neovim
echo 'Install neovim'
echo '--------------'
curl https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage --output nvim.appimage
chmod u+x nvim.appimage && ./nvim.appimage
sudo mv nvim.appimage /usr/local/bin

# Install intelephense
echo 'Install intelephense'
echo '--------------------'
npm i -g intelephense
echo '--------------------'
echo 'Please provide your intelephense key'
read -s -p INTELEPHENSE_KEY
if test -z "$INTELEPHENSE_KEY"; then
    echo 'Creating licence.txt...'
    echo $INTELEPHENSE_KEY > $HOME/intelephense/licence.txt
    echo 'Created licence.txt in ${HOME}/intelephense/licence.txt!'
else
    echo 'Skipping intelephense premium configuration.'
    echo 'See https://github.com/yaegassy/coc-intelephense#enabling-the-premium-feature'
fi

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/.zshrc $HOME/.zshrc

# Symlink neovim prefs
rm -rf $HOME/.config/nvim/
ln -s $HOME/.dotfiles/nvim $HOME/.config/

# Install starship
curl -sS https://starship.rs/install.sh | sh

# Change shell to ZSH
chsh -s $(which zsh)

echo ''
echo 'All done!'
echo ''
echo 'We have tried our best to install everything, but who knows how well it worked.'
echo 'When you first load neovim it will try to install vim-plug, but you will still need to run :PlugInstall'
